### ISSUE TITLE
Template support

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#135]
**Implementation notes:**

We would need a new database `template` table. Would just store an `_id`, `account_id` and `text` column. The `text` should be encrypted.

I want to keep these a transparent feature, no settings or overflow menu for them.

I plan to put them down in the "Attach" section of the message list. I would like to add an icon next to the location option, from there, we would load the templates from the database and display them on a list, then there should be a FAB that allows you to write a new template.

**Todo**
- [x] Server: Create migration to add template table (https://github.com/klinker41/messenger-server/commit/ac6a6868c0daff3e7134a946161b2a7319bd2707)
- [x] Server: Add controller with new routes (https://github.com/klinker41/messenger-server/pull/17)
- [x] Android: Add database tables (https://github.com/klinker41/messenger/commit/1a622bee1138cddf4e84a687394e7c5d021d8237)
- [x] Android: Add API methods (https://github.com/klinker41/messenger/commit/2422ddff44901e25a5ee310ab73b815f2f1ffdb1)
- [x] Android: Add CRUD methods (https://github.com/klinker41/messenger/commit/2422ddff44901e25a5ee310ab73b815f2f1ffdb1)
- [x] Android: Receive FCM events (https://github.com/klinker41/messenger/commit/5b785debade8b34a58dcaeff9dd9fbf01b8c6bfe)
- [x] Android: Download templates when logging in (https://github.com/klinker41/messenger/commit/a2f6148a293499ae71fae2e5b23afce1e4e859a4)
- [x] Android: Upload templates when signing up (https://github.com/klinker41/messenger/commit/a2f6148a293499ae71fae2e5b23afce1e4e859a4)
- [x] Android: UI for managing templates in the attachment menu (fab to add, long click to delete) (https://github.com/klinker41/messenger/commit/6d2a5cce6bff000371eb7dad029c8c8cbbd5097a, https://github.com/klinker41/messenger/commit/2f8d833087c5c7b56e21a6679e924e4239acdd38, https://github.com/klinker41/messenger/commit/f8594b4c88cd95d13a35365d8e73281fd8f5079b, 
 https://github.com/klinker41/messenger/commit/ba7ab2b9972a46fab393c40e10c78fc60293f5e9)
- [x] Web: UI managing the templates, similar to contacts and drafts (https://github.com/klinker41/messenger-web/pull/16)
- [x] Web: Admin UI to see the number of templates (https://github.com/klinker41/messenger-web/commit/ffbae03da827ced39524eda3a5e44a954470479e, https://github.com/klinker41/messenger-server/commit/7a8b174a7e1e4e3826a9993743ab2c4a6d0aea30)
- [x] Web: UI for adding a new template (from the Manage Templates page) (https://github.com/klinker41/messenger-web/commit/d3c12412035be7a7f217ee148168328ee47f07a9, https://github.com/klinker41/messenger-web/commit/b966c0d22438536a801932c16e5774125fcce424)

Some other notes:
- [x] Remember to clear this table as well, or else deleting accounts will fail (https://github.com/klinker41/messenger-server/commit/c9892137cc7f31f38a209b96b39541b81df35e75)

**Comment by klinker24** [comment]
Add migration to create table in backend: https://github.com/klinker41/messenger-server/commit/ac6a6868c0daff3e7134a946161b2a7319bd2707

**Comment by klinker24** [comment]
Will be released with `v2.8.0`.
