### ISSUE TITLE
Blacklist phrases

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#168]
**Request:**

We are able to block by a phone number right now, would be good to be able to block by a phrase (keyword) too.

This change could be pretty involved and full stack.

Another user suggest blacklisting phone numbers by regular expressions. I think that the keyword blacklist is a better direction here, though.

Another suggestion was to have a setting to blacklist all unknown phone numbers. Some people get a ton of spam, I guess.

## TODO

**Setup:**
- [x] Add a column for `phrase` to the `blacklist` table on the backend (https://github.com/klinker41/messenger-server/commit/322cfdee168dd325980f6fbece26b8a9e1cb1ac5)
- [x] Add the `phrase` column to the backend APIs (https://github.com/klinker41/messenger-server/commit/322cfdee168dd325980f6fbece26b8a9e1cb1ac5)
- [x] Add the `phrase` column to the backend FCM notifications (https://github.com/klinker41/messenger-server/commit/322cfdee168dd325980f6fbece26b8a9e1cb1ac5)
- [x] Add the `phrase` column to the Android data model (https://github.com/klinker41/messenger/commit/a861a13fa51a2a23e06057ca28079df21d5a6dde)
- [x] Add the `phrase` to the Android APIs (https://github.com/klinker41/messenger/commit/a861a13fa51a2a23e06057ca28079df21d5a6dde)
- [x] Add the `phrase` to the Android FCM receiver (https://github.com/klinker41/messenger/commit/a861a13fa51a2a23e06057ca28079df21d5a6dde)
- [x] Make sure the `phrase` is encrypted in Android (https://github.com/klinker41/messenger/commit/a861a13fa51a2a23e06057ca28079df21d5a6dde)
- [x] Decrypt the `phrase` when downloading on the web (https://github.com/klinker-apps/messenger-web/commit/716ee146ff348f6d4595f49a89a7e1e17af05d79)

**Background Work:**
- [x] Android: Implement the `phrase` column when checking to see if a message should be saved or not (https://github.com/klinker41/messenger/commit/ceba8625f76e79c85114dea8e322282a47bc1d56)
- [x] Android: implement adapter work around showing the phrase (https://github.com/klinker41/messenger/commit/a861a13fa51a2a23e06057ca28079df21d5a6dde)
- [x] Android: allow deleting the phrases (https://github.com/klinker41/messenger/commit/a861a13fa51a2a23e06057ca28079df21d5a6dde)
- [x] Web: implement view related work for displaying the phrase (https://github.com/klinker-apps/messenger-web/commit/26f112d76fe5f435250a155cb8796e424ae3c324)
- [x] Web: allow deleting the phrases (for free)
- [x] iOS: view phrases in blacklist (https://github.com/klinker-apps/messenger-ios/commit/c931af2b996800e63f2a10f1d8758e905248455c)
- [x] iOS: delete phrases in blacklists (for free)

**Main Interface:**
- [x] Make an Android UI for blacklisting by `phase` instead of just phone number (https://github.com/klinker41/messenger/commit/ded2fa197c33272a6464816d34004d89005ab738)
  - when the user touches the FAB, there is a dialog displayed to create the blacklist by phone number. The easiest way would probably just be to add a new button for "Enter phrase" that switches to blacklisting by phrase
  - we want to make sure that hitting the "blacklist contact" option in the conversation still works (no changes should be needed)
- [x] Make a web UI for blacklisting by `phrase` instead of just phone number (https://github.com/klinker-apps/messenger-web/pull/63)

**Comment by CoachEgghead** [comment]
Is there anyway to link into the blacklist on Google's Messages?  I just switched and have a lot of numbers blocked (spammers) in Messages but Pulse is a clean slate.  I do like the keyword though as a majority of mine are being sent as if I'm someone else.

**Comment by klinker24** [comment]
No that won't be possible, sorry. I don't have access to their blacklist provider and they won't be able to get access to mine.

**Comment by klinker24** [comment]
This will be rolled out in `v4.5.0` of the Android app.

**Comment by Morganizer** [comment]
Liked “
^^ Example of how to blacklist iMessage likes and loves.  Note, it is not a regular " but instead “
