### ISSUE TITLE
Schedule messages with media

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#224]
Within the scheduled message dialog, there should be a way to attach an image (or search for a GIF). I don't think that any other types of media will really make sense. 

I am not going to upload these media files to the web, or expose a way to schedule media, from the web app or other platforms, this will be exclusive to Android. Other platforms will just say *"View media message on the phone app"*, or something similar

### Implementation notes:

* In the dialog where the user types their message, there should be a button to attach an image or GIF. I will just use the "neutral" button on the alert dialog.
  * I will have to pull them from the activity results and re-show the dialog.
  * If an attachment is added, then the neutral button should be "remove image" instead of "attach image"
  * When clicking the button it should prompt the user if they want to attach a GIF vs an image
  * I need to make sure that the images are written into content URIs for safe-keeping
* The images can just be a separate scheduled message entity. 
* When long clicking or tapping the media entity, there should just be a way to delete it, instead of editing it.
* I will need to update the sending service to allow for MMS
* If the media was deleted... Don't send the message
* There is already a database field for the mime type

### TODO:

* [x] Android: UI for attaching images to the scheduled messages
* [x] Android: search for GIFs to attach to the messages
* [x] Android: UI for displaying the image within the scheduled message list
* [x] Android: The sending service will need to support different mime types
* [x] Android: UI for deleting the scheduled message
* [x] Web: Don't try to parse the content of a scheduled message, just display *"View media message on the phone app"*
