### ISSUE TITLE
Folder support

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#298]
**Request:** 

I like the way that Inbox is able to organize things in different folders. I don't think that I will implement them the same way as that, but it would be cool to have other ways to organize your messages in Pulse.

Folders will just be added organization on top of the "conversation list", "archived conversations", and the "private conversations". This feature should be completely independent of those implementations.

**Implementation Notes:**

In the nav drawer, I will make a new section for folders. It should have an item labeled "Manage folders". Clicking that will pop up an activity to rearrange, create, and edit folders. It will also have a list of conversations that can be checked, and added to the folder (private conversations not included).

I will not be changing the implementation of the conversation list and archive list. Conversation's should still have everything. These will just be in addition to those sections. The folders will not care if the conversations are archived or not, they will show everything. The folders will not show any private conversations. Each conversation can only go in one folder.

~I would like to allow the user to be able to color these folder's differently as well. When they enter the folder, it would set the app bar color, recents entry color, status bar color, and the fab color, according to the colors the user has defined. I still want to have the normal conversation colors apply here, though.~

~Folder coloring~
~Deactivate notifications for a folder~

These should sync across Android devices, and the web. On the web, there may just need to be a new "Folders" option in the nav drawer. I don't think that those folders should be added directly to that page.

**Developer Notes:**

We will need to make a new database table for this. The `folder` table will have an `_id`, `device_id`, `title`, `color`, `color_light`, `color_dark`, and `color_accent`.

Each conversation will need a `folder_id` added to it, which will point to the `device_id`. We will then be able to query conversations, according to the `folder_id`.

Inside a `FolderController`, we will need some routes:
- `GET folders#index`
- `POST folders#add`
- `POST folders#delete`
- `POST folders#update`

Inside the `ConversationController`, we will need some routes:
- `POST conversations#add_to_folder` (accept a list of conversations)
- `POST conversations#remove_from_folder` (accept a list of conversations)
- `GET conversations#folder`

**Todo**
- [x] Server: Create migration to add `folder` table
- [x] Server: Add `FolderController` (https://github.com/klinker41/messenger-server/pull/16)
- [x] Server: Create migration to add `folder_id` column to `conversation` table (https://github.com/klinker41/messenger-server/commit/d2e6900f59669a27532ce32409d4f49844ef1830)
- [x] Server: Add routes to `ConversationController` (https://github.com/klinker41/messenger-server/pull/21, https://github.com/klinker41/messenger-server/pull/20, https://github.com/klinker41/messenger-server/pull/19)
- [x] Android: Add database table for `folders` (https://github.com/klinker41/messenger/commit/298c33150d85ebf65dcbf212667d1077491bebb0)
- [x] Android: Create folder API methods (https://github.com/klinker41/messenger/commit/298c33150d85ebf65dcbf212667d1077491bebb0)
- [x] Android: Add CRUD operations for `folders` table (https://github.com/klinker41/messenger/commit/0b947e43c0f795f4f18735301ee8b96b532d7f22)
- [x] Android: Add optional `folder_id` column to `conversations` (https://github.com/klinker41/messenger/commit/0b947e43c0f795f4f18735301ee8b96b532d7f22)
  * This should be indexed
- [x] Android: Add database modifiers for updating the `folder_id` (https://github.com/klinker41/messenger/commit/0ed267972b85b64a954ab2d5fb7d625888fb160d)
- [x] Android: Add API methods for managing the `folder_id` (https://github.com/klinker41/messenger/commit/0ed267972b85b64a954ab2d5fb7d625888fb160d)
- [x] Android: Create a `FolderConversationListFragment` (similar to the `PrivateConversationListFragment`) (https://github.com/klinker41/messenger/commit/6710dfd902d8864e58244713e868a4c6f812ae7d)
- [x] Android: Add database method to query folders (doesn't care about archive status, but shouldn't display private conversations) (https://github.com/klinker41/messenger/commit/6710dfd902d8864e58244713e868a4c6f812ae7d)
- [x] Android: integrate adding the folders to the drawer. Implement the clicks through the `DrawerItemHelper` class (https://github.com/klinker41/messenger/commit/d35c4d1ac878b3cecf3a49c2018dbd236188515e)
- [x] Android: UI/Settings for managing folders (https://github.com/klinker41/messenger/commit/63e338c6ee31cfd6c0e60a625396918db2c4bed3, https://github.com/klinker41/messenger/commit/c4c52dcff12a2971731d0fced39043a5ba9cee41, https://github.com/klinker41/messenger/commit/78b260327a4f05c343164e6d644be443da3354b6, https://github.com/klinker41/messenger/commit/5790511a8eb11c8a93f88d9391476342ee465a0e, https://github.com/klinker41/messenger/commit/954c5f0f9eac74065b84e10b99e2e872d558d045)
  * This will just have an alphabetically sorted list of folders.
  * Clicking a folder will pop up a dialog where you can change the title, select from the list of conversations, "Save", and "Delete".
    * This list should show all conversations, including archived, private, and any conversation already in a folder.
    * If that conversation is already in another folder, it should be disabled and have a line saying "Already in a folder".
    * If that conversation is private, it should be disabled and have a line saying "Private conversation"
  * There needs to be a floating action button to create a new folder.
  * I don't want folder-level notification customization. That is too much, too confusing, and too many different levels. It will just be global or per-conversation.
- [x] Android: within a conversation's settings menu, there should be a new preference for which folder that conversation is in (default being none) (https://github.com/klinker41/messenger/commit/fe80d7fee26bb64cc594de898ab10d891ef1dfb6, https://github.com/klinker41/messenger/commit/f6e25dc4dbfb14960ba57342e7ba8184f796790e)
- [x] Android: Receive FCM events for `folder` events (https://github.com/klinker41/messenger/commit/5b785debade8b34a58dcaeff9dd9fbf01b8c6bfe)
- [x] Android: Receive FCM events for `conversation.folder_id` changes (https://github.com/klinker41/messenger/commit/995c2789096584798c9209362dccd11285c20986)
- [x] Android: download folders in the API download service (https://github.com/klinker41/messenger/commit/a2f6148a293499ae71fae2e5b23afce1e4e859a4)
- [x] Android: upload folder when signing up (https://github.com/klinker41/messenger/commit/a2f6148a293499ae71fae2e5b23afce1e4e859a4)
- [x] Web: UI for viewing conversations in a folder (https://github.com/klinker41/messenger-web/pull/17)
- [x] Web: UI for removing folders (under my account/manage screen) (https://github.com/klinker41/messenger-web/pull/17)
- [x] Web: Admin UI to see the number of folders (https://github.com/klinker41/messenger-web/commit/ffbae03da827ced39524eda3a5e44a954470479e, https://github.com/klinker41/messenger-server/commit/7a8b174a7e1e4e3826a9993743ab2c4a6d0aea30)
- [x] Server and Android: Ensure that deleting a folder removes any references in the `conversation.folder_id` column. This will need to be done before removing the folder, on the backend (https://github.com/klinker41/messenger/commit/b7ce9c6aa1205cc9b4064cb7751b67ba7fc729c3,
 https://github.com/klinker41/messenger-server/commit/02b2061cb4423df4b6f257b226a6b4222d9ce510)

Some other notes:
- [x] Remember to clear this table as well, or else deleting accounts will fail (https://github.com/klinker41/messenger-server/commit/c9892137cc7f31f38a209b96b39541b81df35e75)
- [x] would be cool to have an unread conversations folder as well (https://github.com/klinker41/messenger/commit/50de21120e1461f9f35516185f36a4f6c29936e8)
- [x] on Android, I need to make sure that the `ConversationListUpdatedReceiver` doesn't add a new item to the current fragments list, when it shouldn't. There is a todo in that class, for this. (https://github.com/klinker41/messenger/commit/50de21120e1461f9f35516185f36a4f6c29936e8)

**Comment by klinker24** [comment]
![device-2018-05-01-074934](https://user-images.githubusercontent.com/4874287/39473410-5a88469a-4d14-11e8-91f9-42f220ffe84b.png)

**Comment by klinker24** [comment]
This is done and will be released with `v3.0.0` of the app.
