### ISSUE TITLE
Repeating scheduled messages

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#3]
**Feature Request:**

Currently scheduled messages can only be set for a single time, in the future there should be additional configuration options for setting repeating:

- `0` = single (no repeating)
- `1` = daily
- `2` = weekly
- `3` = monthly
- `4` = yearly

## TODO

**Prep Work**

* [x] backend: add `repeat` column to the scheduled messages
* [x] backend: return the `repeat` column throughout the API
* [x] android: add `repeat` to the database
* [x] android: accept `repeat` throughout the APIs
* [x] android: handle `repeat` in Firebase
* [x] android: handle `repeat` throughout the `DataSource`
* [x] android: handle `repeat` by creating another instance of the message, when sending the scheduled message

**User-side Implementation**

* [x] android: display repeat status in the scheduled messages list
* [x] android: display repeat spinner when creating the scheduled messages
* [x] android: allow for editing the repeat status
* [x] web: display repeat status in the scheduled messages list
* [x] web: allow for creating scheduled messages with this repeat status
* [x] web: edit the repeat status

**Comment by PostaQ** [comment]
That would be a great addition

**Comment by PostaQ** [comment]
That would be a great addition

**Comment by shljad** [comment]
Agreed. Would like to incorporate the functionality that I currently am getting from SMS Scheduler (Quizmoquip) but incorporated into my regular SMS program. Would be happy to sign up for beta testing.

**Comment by skeewi** [comment]
This would be a great feature to add.

**Comment by klinker24** [comment]
This is done. It will be released with `v4.6.0`.
