### ISSUE TITLE
Auto reply system

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#359]
**Request:**

I have had a few request for setting up an auto reply system, for if the user is on vacation and doesn't want to answer right away.

I would like to take this a step further than just an vacation response feature, though. I would like to set up a more comprehensive auto-reply system. Things I can think of:

* Vacation (out of office) responses
* driving mode response (and a quick settings tile to turn it on)
* Keyword matcher responses
* Individual contact responses

**Possible solution:**

This is pretty straight-forward. On the primary device (or if they don't have an account), this would go in the `SmsReceivedReceiver`.

This could go in the `Advanced Features` section of the app and should obviously be synced and editable across all the user's devices.

These should probably be stored in a table on the backend, rather than just `SharedPreferences`. That makes them easier to work with and easier to expand on. The table would have:

* `account_id`: identifier for the user
* `device_id`: id of the item on the primary device
* `type`: `vacation`, `driving_mode`, `keyword`, `contact`, etc...
* `pattern`: (optional) used for `keyword` and `contact` types (encrypted)
* `response`: the text that should be sent (encrypted)

**TODO:**

* [x] backend: create table (https://github.com/klinker41/messenger-server/commit/10a44dcdff4d092a483bd786917e55ad6f7e1acc)
* [x] backend: create REST endpoints (https://github.com/klinker41/messenger-server/commit/2fd9b70866773e281afa5cd0aed0d2e6ad1295b4)
* [x] backend: document the table structure, APIs, and firebase messages
* [x] backend: return the number of auto responses in the database, through the admin counts query (https://github.com/klinker41/messenger-server/commit/91ba04f8ea1d8aa3b1611d59d51117a88aef5a43)
* [x] web: display the number of auto responses through the admin page (https://github.com/klinker41/messenger-web/commit/c6dc5d585f42e10e1242f3aca44267e8e334bdb5)
* [x] android: create table (https://github.com/klinker41/messenger/commit/9d6aad6baff3062de62afe00aaa3f5def7607a19)
* [x] android: implement APIs (https://github.com/klinker41/messenger/commit/9d6aad6baff3062de62afe00aaa3f5def7607a19)
* [x] android: implement CRUD operations (https://github.com/klinker41/messenger/commit/9d6aad6baff3062de62afe00aaa3f5def7607a19)
* [x] android: handle firebase messages (https://github.com/klinker41/messenger/commit/45626c9c11ab761809f51046c2b464d1fd58f74f)
* [x] android: upload and download on account sign in/create (https://github.com/klinker41/messenger/commit/c0a39461b97db401bea8048b56686dc257693336)
* [x] android: create feature toggle for `2.10.0` (https://github.com/klinker41/messenger/commit/d327995fc8709879daa0eff9f5866d0488effa02)
* [x] android: implement within the `SmsReceivedReceiver` (https://github.com/klinker41/messenger/commit/98d09213aa439b0f87f9f9be0665f1d5f684b931)
* [x] android: create settings page (https://github.com/klinker41/messenger/commit/af026816a5331da63579b1c4255c7180b688814d)
* [x] android: implement the driving mode and vacation mode preferences (https://github.com/klinker41/messenger/commit/ab8ed526e0e2cf23bb317c909297dacc1c7d3090)
* [x] android: implement the UI for the keyword and contact auto-replies (https://github.com/klinker41/messenger/commit/64abd62ccf2cb3f9e19178a76fcc680739a28479, https://github.com/klinker41/messenger/commit/7ae90482652cc4d2ad6ad6f8b1a57b11043b0fc1, https://github.com/klinker41/messenger/commit/46c637b9d296a5f6c6a5adc2c4ee2513ccffac6d)
* [x] android: quick settings tile for driving mode (https://github.com/klinker41/messenger/commit/bef257e1f8addd0831bcb52fd21484f87c760f98)
* [x] web: make a page to view and delete these values (https://github.com/klinker41/messenger-server/commit/84b8a915433fcea44b61b63588b0ff2f385354b3, https://github.com/klinker41/messenger-web/commit/c6dc5d585f42e10e1242f3aca44267e8e334bdb5, https://github.com/klinker41/messenger-web/commit/cd3df93fdf1fce9d6edcc67a384f05840e0c3b92)

**Comment by EricCJaffe** [comment]
I would like to reiterate that this would be an awesome feature that would be very high on my list for seeing get developed - it would make it a more perfect app.

**Comment by klinker24** [comment]
This is now finished. After testing and continuous improvements, it is planned to be released in `v2.10.0`.
