### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#493]
**Device with issue:** Native Desktop Platforms
**Request:**

All desktop platforms have a "tray". On windows, it is typically in the bottom right corner, on Mac/Linux, it is typically in the top right of the menu bar:

![screen shot 2017-11-01 at 3 52 35 pm](https://user-images.githubusercontent.com/4874287/32297276-b39c946a-bf1c-11e7-833b-6c9a05fcbc61.png)

Please see the comments below about how this option works for your system (MacOS, Windows, and Linux).

**Implementation Details:**

These may be relevant: 

https://github.com/mattermost/desktop/pull/43
https://stackoverflow.com/a/38980563

This option should be applied to all platforms. It would be good to make an option for this functionality, some people may not like this and want to keep it clean.

**Todo:**

* [x] `MacOS` implementation ("show in menu bar")
* [x] `Windows` implementation ("show in tray")
* [x] `Linux` implementation ("show in tray")
* [x] use proper icons: http://electron.rocks/proper-tray-icon/ (https://github.com/klinker41/messenger-chrome/commit/76245495cc81ccc9cd66a9230d5ee86ab2b2ea95)
* [x] apply the `setTitle` function for the unread count on MacOS (https://github.com/klinker41/messenger-chrome/commit/5685587aa6acca0667ae5842fdfcec333ff76481)

**Comment by klinker24** [comment]
The mac implementation is done: https://github.com/klinker41/messenger-chrome/commit/d85c78c94f2f8c0907a83a6c9619b33fcd96658d

It creates a `Show in Menu Bar` preference.
* When this preference is on:
  * the Pulse icon gets shown in the menu bar
  * Minimizing the app will minimize it to the dock
  * Closing the app will hide the dock icon, in favor of the menu bar icon. The app can be restored from the menu bar. If you have used `macOS` "keep in dock" option on the Pulse icon, it will remain in the dock without the "running" indicator next to it.
* When the preference is off:
  * the Pulse icon is not shown in the menu bar
  * Minimizing the app will minimize it to the dock
  * Closing the app will keep the dock icon active to indicate the app is running (for the notifications)

**Comment by klinker24** [comment]
The Windows and Linux implementation is done: https://github.com/klinker41/messenger-chrome/commit/c2e69fb7be3b4ffea1d8cb36830fcca3e4a3cd21, https://github.com/klinker41/messenger-chrome/commit/e5d3c2e5651b0eb5006c8db10009fc7ef6ca0288

The Windows and Linux behavior is identical.

----

This creates a `Show in Tray` preference. The tray is the part of the dock/bar near where your clock is at. There are other icons such as WiFi, bluetooth, etc there.

* When this preference is on:
  * the Pulse icon gets shown in the tray
  * Minimizing the app will minimize it to the dock, as usual
  * Closing the app will hide the dock icon, in favor of the tray icon. The app can be restored from the tray. If you have used the "keep in dock" option on the Pulse icon, it will remain in the dock.
* When the preference is off:
  * the Pulse icon is not shown in the tray
  * Minimizing the app will minimize it to the dock
  * Closing the app stop all background process. This means that you will no longer receive notifications from the Pulse app on your computer.


> Turning off this preference prevents the app from running in the background. That means your computer will not receive any notifications in Pulse. So, turning this preference off does affect functionality.

> This is **turned on** by default.

**Comment by klinker24** [comment]
This is now done. I have closed comments on it, because I want to use it as a reference page to point people to, for how this option works across the different platforms.
