### ISSUE TITLE
Per-person coloring

### ISSUE THREAD

**Issue by kirstilynn** [klinker-apps/messenger-issues#496]
I love the text color per user that the mobile application has. It is especially great in group texts. It would be awesome if the desktop application maintained those same text colors in the group texts.

It would also be awesome to be able to edit those conversation customizations from the desktop as well.

Thanks for the awesome app!

**Comment by klinker24** [comment]
I doubt that editing the conversation settings will come to the desktop platforms. 

Someday, it will get the per-person coloring though, yes. There are quite a few barriers in the way of that right now.

**Comment by klinker24** [comment]
**Phone**
* track id matcher in `contacts` table: https://github.com/klinker41/messenger/commit/2d49c178ba9c51a4efb1765c51f71de8a27600e3
* push the new field to the backend: https://github.com/klinker41/messenger/commit/4f7e9a49239a532c744171aa95fff579b7491082

**Backend**
* track and provide contact matcher through the simple contact serializer: https://github.com/klinker41/messenger-server/commit/6cc27ae7f5a6f5b8838b175c3997914b8df75824

**Web**
* decrypt the id matcher: https://github.com/klinker41/messenger-web/commit/fd3d7cf3e0174daea6802bba0be856fdbecd6d40

----

**Todo**
* [ ] Backend: provide the primary color through the simple contact serializer
* [ ] Web: provide the contact list across conversations
* [ ] Web: create eight-character id matcher pattern based on the phone numbers of a conversation
* [ ] Web: use the generated id matcher patterns to map contact entries to the `from` field on the message
* [ ] Web: use the mapped contacts to colorize the messages

**Comment by klinker24** [comment]
I have finished this on the web, with this series of commits: 

- revamp of contact querying: https://github.com/klinker41/messenger-web/commit/175f4e6f10fc08ac14905ca3dd697511b58b7ba1
- map contacts to colors: https://github.com/klinker41/messenger-web/commit/68801f49dedef41b2e2e1171ae8c194a3745e81f
- use the color map for the contacts: https://github.com/klinker41/messenger-web/commit/b898bffaaa5a4f00ead2f3e71127970aab1dd1c4

I am closing this out, it is finished, but I am not ready to release it yet. There are some changes that need to be pushed up to Android, before it can hit everyone.

**Comment by klinker24** [comment]
This is rolling out to everyone, on the web: https://github.com/klinker41/messenger-web/commit/c9238f171ca98d652efe0936289efe5b0e8ecf6e
