### ISSUE TITLE
Add contact targets to quick compose

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#503]
**Request:**

I recently finished adding a quick compose functionality (#72).

To add on to this, I would like to allow for up to three "Favorite" contacts that are available as notification actions on this quick text notification. Right now, it is just a plain notification, but there is really no drawback in adding this functionality.

**Additional information:**

I would want to change the settings. Right now it is just a single switch preference. I will need to turn it in to a category with the switch turning it on and off, then a preference to select up to 3 contacts.

I will probably just store these in the shared preferences, so that it is easy to share between Android devices. These won't have any web integration.

**Todo:**

* [x] Make the settings UI changes to support the favorite user preference (https://github.com/klinker41/messenger/commit/dce8b40eb08cc2702a2460b5f3152342b30a040e)
* [x] Implement the dialog/UI to select up to 3 contacts using the `RecipientEditTextView` (https://github.com/klinker41/messenger/commit/7668f901458b551d650daf7e232b5bc098a118da)
* [x] Persist the list of contacts to `SharedPreferences` (https://github.com/klinker41/messenger/commit/745e76500816a2486bd3ef0b2c49446ce2b0bc85)
  * We really just need to share the numbers, since we can use that to look up the thumbnail and name
  * [x] Share the list of numbers between Pulse devices
* [x] Re-display the selected contacts when the user opens the preference again (https://github.com/klinker41/messenger/commit/0a0dfe8f6fb37530a68e827dc6fed24949c58a8b)
* [ ] Apply this list to the notification actions in the `QuickComposeNotificationService`

**Comment by klinker24** [comment]
Settings page for the advanced features:

![settings](https://user-images.githubusercontent.com/4874287/32692300-2aa0a324-c6db-11e7-9ea2-1d7bdaa33eee.png)

**Comment by klinker24** [comment]
Select contacts UI: 

![select_contacts](https://user-images.githubusercontent.com/4874287/32692725-ecc99d46-c6e2-11e7-80b8-1350531f0ab0.png)

**Comment by klinker24** [comment]
Here is the notification with the actions:

![notification](https://user-images.githubusercontent.com/4874287/32699515-bb15e6de-c77c-11e7-9064-21303f9ed568.png)

On Oreo, the notification is in its compressed state by default. On other versions of Android, it is a hidden notification with the lowest priority.

**Comment by klinker24** [comment]
I am really happy about how this quick text feature turned out and its implications on sharing as well :)

This will be a welcome addition to the app for everyone, regardless of if they use the persistent notification or not. Most will not use that.
