### ISSUE TITLE
Contact management improvements

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#620]
**Feature Requests:**

On the web: 
1. I want to display contact groups when composing new messages
2. I want to display the type of the number, when composing new messages (mobile, home, work, other)

On all platforms:
1. If the contact has a nickname defined, it should be shown in the app (#688)

**Additional information:**

1. Just query the contact groups from the upload contacts service and insert them into the contacts table. The numbers just need to have `;` between them.

2. Will need to add a new column to Android and the backend to hold the number type

* `0` = group
* `1` = home
* `2` = mobile
* `3` = work
* `4`+ = other

**Bug Report:**

I also heard from a user that not all of his mobile contacts were uploaded, when the app was first installed.

## TODO

* [x] backend: add `contact.contact_type` to the database
* [x] backend: handle `contact.contact_type` when creating contact records
* [x] web: download and persist types with the contact records
* [x] web: display contact types when composing messages
* [x] android: add `contact.type` to the database
* [x] android:  write the contacts type when querying contacts
* [x] android: handle `type` param within FCM messages
* [x] android: query and persist groups (with type = 0)
* [x] android: re-upload contacts with type information and groups

**Comment by klinker24** [comment]
The changes around contacts will be included in `v2.5.2` of the Android app. When this version is installed on the user's device, it will re-upload all of the contacts, with the type information, as well as the groups. To download those contacts to the web app, the user will still need to hit the refresh button on the compose page. 

I have not deployed the related web/desktop app changes, yet.
