### ISSUE TITLE
Improve quick compose functionality

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#72]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.2.283

**Information:**

Some messaging apps allow for a notification to be shown at all times and when clicked on, you can compose a message, send it, and then go back to what you were doing without leaving the current task. The ui for this could be similar to the quick reply, just with a contact entry area at the top instead of message history. We could use the recipient edit text to make this as easy as possible.

**Todo:**

* [x] Figure out when this quick share should be used (quick settings, always-on notification, sharing to Pulse, launcher shortcuts)
  * [x] Integrate quick share activity wherever it should be used
* [x] Create the UI for the activity
* [x] Send text messages
* [x] Handle text-based share intent data
* [x] Handle image-based share intent data
* [x] Handle audio, video, and vcard share intent data
* [x] Move the direct share targets to use this activity instead of the compose activity
* [x] Create persistent notification functionality
  * start the notification from: FCM receiver, on boot, preference switch
  * stop the notification from: FCM receiver, preference switch

**Comment by klinker24** [comment]
I have added a quick settings tile for Android N. It simply opens the compose activity, but could easily shift to doing something like this instead, if we made a new activity that acted as a popup.

This also means that if we add a settings option for "Quick Compose", we should remove that setting on Android 7.0+ since it will be redundant.

**Comment by klinker24** [comment]
Some other notes on this: 

* It would be great to use it for a faster "share" as well. Right now, when sharing content, it opens the full app, you enter the contact name, then it adds a draft message for that content. Which is quite a few steps
  * This could definitely be applied to direct share as well
* Integrate it into the launcher shortcut for composing a message

So, to summarize, I would like to apply this to: `Quick Settings Tile`, `Always-on Notification`, `Sharing`, `Launcher Shortcuts`.

I also think that I will make it available on Android 7.0+, since there is such little visibility around the quick settings tiles. I don't see much reason to hide it

**Comment by klinker24** [comment]
Some notes as I am thinking about this:

* I don't want to change the compose Activity's implementation at all.
  * Right now, it hands sharing as well as direct share targets
  * It should continue to be able to do this, for users that want to open the full app. 
  * Its name in the share menu is just `Pulse`, which shouldn't change
* I want to add a new activity called `Quick Share`.
  * It should only handle the `SEND` intent, and not handle the `sms:`, `smsto:` data queries or `VIEW` intents. Those should continue to go through the compose screen, since it will immediately open the conversation to that user, instead of just sharing a single message.
  * This makes sense to me, because when clicking on a link, it is viewing the content, not sharing the content.

For the UI, I may use the [Floating Tutorial](https://github.com/klinker24/Android-FloatingTutorialActivity) style. I do need to make sure that it can handle all types of media and provide previews for these different types. It should not have any of the `ChooserTargetService` integration. Those will continue to go through the compose menu.

```xml
<intent-filter>
    <action android:name="android.intent.action.SEND" />
    <category android:name="android.intent.category.DEFAULT" />

    <data android:mimeType="text/plain" />
    <data android:mimeType="text/vcard" />
    <data android:mimeType="text/x-vcard" />
    <data android:mimeType="image/*" />
    <data android:mimeType="audio/*" />
    <data android:mimeType="video/*" />
</intent-filter>
```

**Comment by klinker24** [comment]
This is almost done. I need to finish up with the persistent notification for composing the message, then I will be able to push this out.

For now, I have commented out and share intents in the `AndroidManifest.xml` and the shortcut code in the `shortcuts.xml`. Those will need to be un-commented before the release.

I also have a feature flag that will need to be removed.

**Comment by klinker24** [comment]
This is now finished. It is still flagged and commented out until I am done with `2.7.0` and ready to release it.

![notification](https://dl2.pushbulletusercontent.com/DoEzDw0rfi1abgWVDpgvmZTJ9f3DJkgm/Screenshot_20171111-081923.png)
![compose](https://dl2.pushbulletusercontent.com/0oNH3ZQrwO3j6cbPRgI6jCNaV2goEmHv/Screenshot_20171111-081943.png)
![share](https://dl2.pushbulletusercontent.com/v8a7hIRq8aKGP50cOyhn6GQrAvMBx6Y7/Screenshot_20171111-082245.png)
