### ISSUE TITLE
Option for whether or not to apply the primary color to the app bar

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#737]
**Feature Request:**

People keep telling me that they like Android Messages new design, but can't really quantify what they want to see changed. 

![image](https://www.androidpolice.com/wp-content/uploads/2018/08/Screenshot_20180816-105508-668x1336.png)

The biggest change between that and Pulse is simply the white app bar (or dark app bar, when using the dark theme). With Pulse, you can apply the white app bar, but it also changes the received message background to white. 

I would like to create a toggle option:

```
Apply Primary Color to App Bar
Whether or not the app bar should be colorized
```

**Additional information:**

Should be very easy to implement, really. I already have the app bar set up to allow for light themes and adjust the font color accordingly.

One thing to think about is whether or not to use the same color on the status bar as the app bar. Android Messages does, and it seems like this is the way that Google has been going.

I will want to track this on the backend and apply it with any new account login. I will also want to push it up when the user creates the account. The same option will need to exist on the web app.

**TODO:**

* android :
  * [x] apply preference and UI changes (https://github.com/klinker41/messenger/commit/1907ff89f8346870460cb6398f183143c15d0098)
  * [x] restore preference on account sign in (https://github.com/klinker41/messenger/commit/35f439ef445c149ee1aa1b9e8c6f12c876077638)
  * [x] push up preference when creating the account (https://github.com/klinker41/messenger/commit/35f439ef445c149ee1aa1b9e8c6f12c876077638)
* backend: 
  * [x] track preference selection on backend (https://github.com/klinker41/messenger-server/commit/492a74f900932e7776cb0577f0ecc1976bb99a0d)
  * [x] provide preference selection through login apis (https://github.com/klinker41/messenger-server/commit/492a74f900932e7776cb0577f0ecc1976bb99a0d)
* web: 
  * [x] make preference in settings menu (https://github.com/klinker-apps/messenger-web/commit/f1ed7448b43d5994c31af54b6712cbb9d2ef1df2)
  * [x] colorize toolbar (https://github.com/klinker-apps/messenger-web/commit/3b0eac759198e2000b33371f4ab993bc9e935ab2)
  * [x] read preference from backend (https://github.com/klinker-apps/messenger-web/commit/d8e70dccec478e6c7e02cedf0d1fe0f8a5bda57b)

**Comment by klinker24** [comment]
This is done. It will be released across the platforms with `v4.1.0`.
